import { NextResponse, type NextRequest } from "next/server";
import { z } from "zod";
import { requirePermission } from "@/modules/identity/application/auth";
import { permissionKeys } from "@/modules/identity/domain/permissions";
import { getDb } from "@/shared/database";
import { assertSameOrigin, handleRouteError, jsonError, requestId } from "@/shared/http";

const schema=z.discriminatedUnion("action",[
  z.object({action:z.literal("create"),name:z.string().trim().min(2).max(60),rank:z.coerce.number().int().min(1).max(99),permissions:z.array(z.enum(permissionKeys)).max(permissionKeys.length)}),
  z.object({action:z.literal("update"),roleId:z.string().cuid(),name:z.string().trim().min(2).max(60),rank:z.coerce.number().int().min(1).max(99),permissions:z.array(z.enum(permissionKeys)).max(permissionKeys.length)}),
  z.object({action:z.literal("delete"),roleId:z.string().cuid()}),
]);

export async function GET(request:NextRequest){const id=requestId(request);try{const context=await requirePermission("roles.manage");if(!context.ok)return jsonError(context.error,id);const db=getDb();const [roles,permissions]=await Promise.all([db.role.findMany({where:{organizationId:context.value.organizationId},include:{permissions:{include:{permission:true}},_count:{select:{memberships:true,invitations:true}}},orderBy:{rank:"desc"}}),db.permission.findMany({where:{key:{in:[...permissionKeys]}},orderBy:{key:"asc"}})]);return NextResponse.json({roles,permissions},{headers:{"x-request-id":id,"cache-control":"private, no-store"}})}catch(error){return handleRouteError(error,id)}}

export async function POST(request:NextRequest){const id=requestId(request);try{if(!assertSameOrigin(request))return jsonError({code:"FORBIDDEN",message:"Origen no permitido."},id);const context=await requirePermission("roles.manage");if(!context.ok)return jsonError(context.error,id);const input=schema.parse(await request.json());const organizationId=context.value.organizationId;const db=getDb();const actor=await db.membership.findUnique({where:{organizationId_userId:{organizationId,userId:context.value.userId}},include:{role:{include:{permissions:{include:{permission:true}}}}}});if(!actor)return jsonError({code:"FORBIDDEN",message:"Membresía no encontrada."},id);const allowed=new Set(actor.role.permissions.map(item=>item.permission.key));
  if(input.action!=="delete"&&(input.rank>=actor.role.rank||input.permissions.some(permission=>!allowed.has(permission))))return jsonError({code:"FORBIDDEN",message:"No puedes crear un rol con rango o permisos superiores a los tuyos."},id);
  const output=await db.$transaction(async tx=>{if(input.action==="delete"){const role=await tx.role.findUnique({where:{organizationId_id:{organizationId,id:input.roleId}},include:{_count:{select:{memberships:true,invitations:true}}}});if(!role)return null;if(role.isSystem||role.rank>=actor.role.rank||role._count.memberships>0||role._count.invitations>0)throw new RoleFailure("El rol es de sistema, supera tu rango o continúa en uso.");await tx.role.delete({where:{organizationId_id:{organizationId,id:role.id}}});await tx.auditEvent.create({data:{organizationId,actorId:context.value.userId,action:"role.delete",resourceType:"Role",resourceId:role.id,outcome:"SUCCESS",correlationId:id}});return{id:role.id}}const role=input.action==="create"?await tx.role.create({data:{organizationId,name:input.name.toUpperCase(),rank:input.rank,isSystem:false}}):await tx.role.update({where:{organizationId_id:{organizationId,id:input.roleId}},data:{name:input.name.toUpperCase(),rank:input.rank}});if(role.isSystem)throw new RoleFailure("Los roles del sistema no pueden modificarse.");await tx.rolePermission.deleteMany({where:{roleId:role.id}});const permissions=await tx.permission.findMany({where:{key:{in:input.permissions}}});await tx.rolePermission.createMany({data:permissions.map(permission=>({roleId:role.id,permissionId:permission.id}))});const affected=await tx.membership.findMany({where:{organizationId,roleId:role.id},select:{userId:true}});if(affected.length)await tx.session.updateMany({where:{userId:{in:affected.map(item=>item.userId)},revokedAt:null},data:{revokedAt:new Date()}});await tx.auditEvent.create({data:{organizationId,actorId:context.value.userId,action:`role.${input.action}`,resourceType:"Role",resourceId:role.id,outcome:"SUCCESS",changes:{name:role.name,rank:role.rank,permissions:input.permissions},correlationId:id}});return{id:role.id}});if(!output)return jsonError({code:"NOT_FOUND",message:"Rol no encontrado."},id);return NextResponse.json({data:output},{status:input.action==="create"?201:200,headers:{"x-request-id":id}})}catch(error){if(error instanceof RoleFailure)return jsonError({code:"CONFLICT",message:error.message},id);return handleRouteError(error,id)}}
class RoleFailure extends Error{}
